---
title: "SEIR simulations for OO"
author: "Andres Colubri"
date: "07/13/2024"
output:
  html_document:
    df_print: paged
---

```{r}
library(doRNG)
library(foreach)
library(doParallel)
library(boot)
library(properties)

# tidyr has to be imported before magrittr so extract() from the latter is used
library(tidyr)

library(dplyr)
library(plyr)
library(reshape2)
library(magrittr)

library(ggplot2)
theme_set(theme_bw())

library(pomp)
stopifnot(packageVersion("pomp")>="2")
```

DATA

```{r}
main_folder <- "./simulations/diseasex"

prop_file = file.path(main_folder, "sim.properties")
prop <- read.properties(prop_file)

output_name <- prop$output_name
output_folder <- file.path(main_folder, output_name)
if (!dir.exists(output_folder)) dir.create(output_folder)
cooking_folder <- file.path(main_folder, output_name, "bake")
if (!dir.exists(cooking_folder)) dir.create(cooking_folder)
plotting_folder <- file.path(main_folder, output_name, "plots")
if (!dir.exists(plotting_folder)) dir.create(plotting_folder)
code_folder <- file.path(main_folder, "code")
if (!dir.exists(code_folder)) dir.create(code_folder)
file_name <- "snippets"
```

PARAMETERS

```{r}

pop_size <- as.integer(as.numeric(prop$pop_size) * as.numeric(prop$susc_frac))
exp0 <- as.integer(prop$exp0)
inf0 <- as.integer(prop$inf0)
rec0 <- as.integer(prop$rec0)

time_step <-as.numeric(prop$time_step)
num_sims <- as.integer(prop$num_sims)

total_time <- as.integer(prop$total_time)

log_trans_params <- c("beta", "psi")
logit_trans_params <- c("gamma", "rho")

all_param_names <- c("pop", "S_0", "E_0", "I_0", "R_0", 
                     "beta", "gamma", "sigma", "rho", "psi")
all_param_values <- c(pop=pop_size, 
                      S_0=1-(exp0+inf0+rec0)/pop_size, E_0=exp0/pop_size, I_0=inf0/pop_size, R_0=rec0/pop_size, 
                      beta=as.numeric(prop$beta),
                      gamma=as.numeric(prop$gamma),
                      sigma=as.numeric(prop$sigma),
                      rho=as.numeric(prop$rho),
                      psi=as.numeric(prop$psi))

# Random seed, keep unchanged to ensure reproducibility of results
test_sim_seed <- as.integer(prop$test_sim_seed)
```

COMPARTMENTAL MODEL

```{r}
# Csnippets defining the SEIR model

# pomp C API:
# https://kingaa.github.io/pomp/vignettes/C_API.html

rproc <- Csnippet("
  double rate[3], trans[3];

  rate[0] = beta * I/pop;
  rate[1] = sigma;
  rate[2] = gamma;

  // transitions between classes
  reulermultinom(1, S, &rate[0], dt, &trans[0]);
  reulermultinom(1, E, &rate[1], dt, &trans[1]);
  reulermultinom(1, I, &rate[2], dt, &trans[2]);

  S += -trans[0];
  E += trans[0] - trans[1];
  I += trans[1] - trans[2];
  R += trans[2];

  // Assigning the right number to the accumulation variable that's used
  // in the observation model is absolutely critical!!!!
  C += trans[2]; // We are observing the number of infectious cases that get quarantined when identified
")

initlz <- Csnippet("
  double m = pop/(S_0 + E_0 + I_0 + R_0);

  S = nearbyint(m*S_0);
  E = nearbyint(m*E_0);
  I = nearbyint(m*I_0);
  R = nearbyint(m*R_0);

  C = 0;
")

dmeas <- Csnippet("
  double m = rho * C;
  double v = m * (1.0 - rho + psi * psi * m);
  double tol = 1.0e-18;
  if (cases > 0.0) {
    lik = pnorm(cases + 0.5, m, sqrt(v) + tol, 1, 0) - pnorm(cases - 0.5, m, sqrt(v)  + tol, 1, 0) + tol;
  } else {
    lik = pnorm(cases + 0.5, m, sqrt(v) + tol, 1, 0) + tol;
  }
  if (give_log) lik = log(lik);
")

rmeas <- Csnippet("
  double m = rho * C;
  double v = m * (1.0 - rho + psi * psi * m);
  double tol = 1.0e-18;
  cases = rnorm(m, sqrt(v) + tol);
  if (cases > 0.0) {
    cases = nearbyint(cases);
  } else {
    cases = 0.0;
  }
")
```

```{r}
set.seed(test_sim_seed)

# POMP model
simulate(t0=0, times=1:total_time,
         rprocess=euler(rproc, delta.t=time_step),
         rinit=initlz,
         rmeasure=rmeas,
         dmeasure=dmeas,
         cdir = code_folder,
         cfile = file_name,       
         accumvars=c("C"),
         statenames=c("S", "E", "I", "R", "C"),
         obsnames=c("cases"),
         partrans=parameter_trans(
           log=log_trans_params,
           logit=logit_trans_params),
         paramnames=all_param_names,
         params=all_param_values,
         verbose = TRUE
) -> mdl_sim

ggplot(data=pivot_longer(as(mdl_sim,"data.frame"),-time),
  aes(x=time,y=value,color=name))+
  geom_line()

ggsave(file.path(plotting_folder, "sample-sim.pdf"))
```

SIMULATIONS

```{r}
# Some utility functions to calculate cumulative case numbers

rem_low_count_simulations <- function(sdat, n) {
  wlim <- 2
  wday <- 7
  
  all_totals <- c()
  for (i in 1:n) {
    sim <- subset(sdat, .id == i)
    tot <- sum(sim$cases)
    sim$week <- floor(sim$time/wday)
    wdat <- data.frame(week = sim$week, cases = sim$cases)
    wdat <- group_by(wdat, week)

    wcases <- c()
    for (w in unique(wdat$week)){
      temp <- subset(wdat, week == w)
      wcases <- c(wcases, sum(temp$cases))
    }
    wdat <- data.frame(week = unique(wdat$week), cases = wcases)
    if (any(wcases[1:(length(wcases)-wlim)] == 0)) {
      sdat <- subset(sdat, .id != i)
    } else{
      all_totals <-  c(all_totals, tot)
    }
  }
  #print(mean(all_totals))
  
  # Make ids consecutive
  uniq <- unique(sdat$.id)
  uid <- 1
  for (u in uniq) {
    if (u == 'data') next
    sdat$.id[sdat$.id == u] <- uid
    uid <- uid + 1  
  }
  
  return(sdat)
}

cumulative_curve <- function(dat, len) {
  total_sum <- 0
  daily_sum <- c()
  for (i in 1:len) {
    total_sum <- total_sum + dat$cases[i]
    daily_sum <- c(daily_sum, total_sum)
  }
  return(daily_sum)
}  
  
median_simulation <- function(sdat, n) {
  all_totals <- c()
  for (i in 1:n) {
    sim <- subset(sdat, .id == i)
    tot <- sum(sim$cases)
    all_totals <- c(all_totals, tot)
  }

  # Taking the median
  n2 <- 0.5 * n
  median_idx <- order(all_totals)[n2]
  median_sim <- subset(sdat, .id == median_idx)
  
  return(median_sim)
}

calc_cumulative_counts <- function(sdat, len) {
  all_csum <- c()
  csum <- NULL
  for (t in 1:len) {
    dt <- subset(sdat, .id != "data" & time == t)
    if (is.null(csum)) {
      csum <- dt$cases
    } else {
      csum <- csum + dt$cases
    }
    
    all_csum <- c(all_csum, csum)
  }
  return(all_csum)
}
```

```{r}
mdl_sim  %>%
  simulate(nsim=num_sims) -> sim_data

ggplot(data=pivot_longer(
         as.data.frame(sim_data),
         c(cases, S, E, I, R, C)
       ),
  aes(x=time,y=value,color=name,
    group=interaction(.L1,name)))+
  geom_line()+
  facet_grid(name~.,scales="free_y")+
  labs(y="",color="")

ggsave(file.path(plotting_folder, "trajectories.pdf"))
```